'use client'

import type { Metadata } from "next";
import "./globals.css";
import { AppWalletProvider } from "./components/AppWalletProvider";
import { ReactQueryProvider } from "./react-query-provider";
import { Provider } from "react-redux";
import {store} from '../app/store'
import Header from "./components/Header";
import { ToastContainer } from "react-toastify";



const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ReactQueryProvider>
          <Provider store={store}>
          <AppWalletProvider>
           
            <Header/>
            <main className="max-w-6xl mx-auto">{children}</main>
              <ToastContainer
                position="bottom-center"
                autoClose={5000}
                hideProgressBar={false}
                newestOnTop={false}
                closeOnClick
                rtl={false}
                pauseOnFocusLoss
                draggable
                pauseOnHover
                theme="dark"
              />
          </AppWalletProvider>
          </Provider>
         </ReactQueryProvider>
      </body>
    </html>
     
       
  );
}
